name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '1 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: go python script
      run: |
        city='${{ secrets.CITY }}'
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        echo "begin to run python script"
        python demo.py $city $user $pwd
        echo "Script Done."
